version: '3'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    command: [ "gunicorn", "-b", "0.0.0.0:8000", "conf.wsgi:application" ]
    volumes:
      - ../..:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  redis:
    image: redis:3

#  postfix:
#    image: catatnight/postfix
#    ports:
#      - "25:25"
#    volumes:
#      - /ruta/a/tus/datos:/data
#
#  dovecot:
#    image: dovecot/dovecot
#    ports:
#      - "143:143"
#    volumes:
#      - /ruta/a/tus/datos:/data

